name: Java CI
  
# 実行タイミング定義
on:
  push:
    branches:
    - master

# ジョブ
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Build with Gradle
      run: ./gradlew build
    - name: Display the path
      run: ls -la ./build/libs/
    - name: Display the path
      run: curl -X POST --data-urlencode "payload={\"channel\": \"#cidi\", \"username\": \"webhookbot\", \"text\": \"これは GGG という名のボットから #cidi に投稿されています。\", \"icon_emoji\": \":ghost:\"}" https://hooks.slack.com/services/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